name: cmake build and test

inputs:
  build-type:
    description: cmake build type
    required: true
    default: debug
  build-dir:
    description: cmake build directory
    required: false
    default: build/${{ build-type }}
  config-option:
    description: cmake config option
    required: false
  vcpkg-root:
    description: vcpkg position
    required: false
    default: ${{ github.workspace }}/.vcpkg

runs:
  using: composite
  steps:
    - name: Setup vcpkg
      id: vcpkg-setup
      uses: lukka/run-vcpkg@v10
      with:
        vcpkgGitCommitId: 9776b51b557bb2c20d79cf541f124c48d0c2c720
        vcpkgDirectory: ${{ inputs.vcpkg-root }}

    - uses: seanmiddleditch/gha-setup-ninja@master
      with:
        destination: ${{ github.workspace }}/.ninja

    - uses: ilammy/msvc-dev-cmd@v1
      if: ${{ runner.os == 'Windows' }}

    - name: Install dependencies and generate project files
      id: cmake-config
      run: cmake -S "${{ github.workspace }}" -B "${{ inputs.build-dir }}" -G Ninja -DCMAKE_TOOLCHAIN_FILE="${{ inputs.vcpkg-root }}/scripts/buildsystems/vcpkg.cmake" -DCMAKE_BUILD_TYPE=${{ inputs.build-type }} ${{ inputs.config-option }}
      shell: bash

    - name: Build
      run: cmake --build "${{ inputs.build-dir }}"
      shell: bash

    - name: Run test
      run: |
        cd ${{ inputs.build-dir }}
        set CTEST_OUTPUT_ON_FAILURE=1
        ctest
      shell: bash
