name: cmake build and test
description: use cmake to build project and run ctest

inputs:
  build-type:
    description: cmake build type
    required: true
    default: debug
  build-dir:
    description: cmake build directory
    required: false
    default: .build
  config-option:
    description: cmake config option
    required: false
  vcpkg-root:
    description: vcpkg position
    required: false
    default: ${{ github.workspace }}/.vcpkg
  before-build:
    description: run before build
    required: false
runs:
  using: composite
  steps:
    - uses: seanmiddleditch/gha-setup-ninja@master
      with:
        destination: ${{ github.workspace }}/.ninja

    - name: Setup vcpkg
      id: vcpkg-setup
      uses: lukka/run-vcpkg@v10
      with:
        vcpkgGitCommitId: 5f82fa45df07a446bab57f65479f3d2df797f408
        vcpkgDirectory: ${{ inputs.vcpkg-root }}

    - uses: ilammy/msvc-dev-cmd@v1
      if: ${{ runner.os == 'Windows' }}

    - name: Run before cmake build
      id: before-cmake-build
      run: ${{ inputs.before-build }}
      shell: bash

    - name: Install dependencies and generate project files
      id: cmake-config
      run: cmake -S "${{ github.workspace }}" -B "${{ inputs.build-dir }}" -G Ninja -DCMAKE_TOOLCHAIN_FILE="${{ inputs.vcpkg-root }}/scripts/buildsystems/vcpkg.cmake" -DCMAKE_BUILD_TYPE=${{ inputs.build-type }} ${{ inputs.config-option }}
      shell: bash

    - name: Build
      run: |
        cmake --build "${{ inputs.build-dir }}" | tee "${{ inputs.build-dir }}/cmake-build.log"
        cat "${{ inputs.build-dir }}/cmake-build.log"
      shell: bash

    - name: Run test
      working-directory: ${{ inputs.build-dir }}
      run: ctest --output-on-failure -C ${{ inputs.build-type }} -T test
      shell: bash
