name: Update MSVC toolchain on Windows

runs:
  using: composite

  steps:
    - run: |
        Invoke-WebRequest https://aka.ms/vs/17/release/vs_enterprise.exe -OutFile setup.exe
        .\setup.exe updateAll --norestart -p | Out-Null
      shell: pwsh
