name: Build

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  job:
    name: ${{ matrix.os }} ${{ matrix.build-type }} build
    runs-on: ${{ matrix.os }}
    continue-on-error: false

    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-22.04, windows-latest]
        build-type: [Debug, Release]
        include:
          - os: ubuntu-22.04
            cmakeOptions: -DCMAKE_CXX_COMPILER=clang++

    steps:
      - uses: actions/checkout@v2

      - name: Upgrade clang on Linux
        if: ${{ runner.os == 'Linux' }}
        run: |
          sudo apt update
          sudo apt upgrade clang

      - name: Upgrade clang on Windows
        if: ${{ runner.os == 'Windows' }}
        working-directory: C:\Program Files (x86)\Microsoft Visual Studio\Installer
        run: .\setup.exe update --installPath "C:\Program Files\Microsoft Visual Studio\2022\Enterprise" -q --norestart
        shell: pwsh

      - uses: ./.github/actions
        with:
          build-type: ${{ matrix.build-type }}
          config-option: ${{ matrix.cmakeOptions }}
