name: Build

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  job:
    name: ${{ matrix.os }} ${{ matrix.build-type }} build
    runs-on: ${{ matrix.os }}
    continue-on-error: false

    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-22.04, windows-latest]
        build-type: [Debug, Release]
        include:
          - os: ubuntu-22.04
            cmakeOptions: -DCMAKE_CXX_COMPILER=clang++

    steps:
      - uses: actions/checkout@v2

      - name: Upgrade Linux packages
        if: ${{ runner.os == 'Linux' }}
        run: |
          sudo apt update
          sudo apt upgrade
          sudo apt install ninja-build

      - name: Upgrade Windows packages
        if: ${{ runner.os == 'Windows' }}
        run: |
          choco upgrade all
          choco install ninja

      - uses: ${{ github.workspace }}/.github/actions/action.yml
        with:
          build-type: ${{ matrix.build-type }}
          config-option: ${{ matrix.cmakeOptions }}
