name: Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  job:          
    name: ${{ matrix.os }} build
    runs-on: ${{ matrix.os }}
    env:
      Target: blurringshadowTests
      buildDir: '${{ github.workspace }}/build'
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest]
        include:
          - os: windows-latest
            triplet: x64-windows
            cmakeOptions: ''
            testOptions: '--test-dir ${{ env.buildDir }}'
          - os: ubuntu-latest
            triplet: x64-linux
            cmakeOptions: -DCMAKE_CXX_COMPILER=g++-11
            testOptions: ''
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      
      - name: Set up G++
        uses: egor-tensin/setup-gcc@v1
        if: ${{ runner.os == 'Linux' }}
        with:
          version: 11
          platform: x64

      - uses: lukka/get-cmake@latest
 
      - name: Restore artifacts, or setup vcpkg (do not install any package)
        uses: lukka/run-vcpkg@main
        id: runvcpkg
        with:
          setupOnly: true
          vcpkgGitCommitId: 'b2544fd780b2e9a05d903314cbbd37268ba43d81'
          # Ensure the cache key changes any time the content of the manifest file changes.
          appendedCacheKey: ${{ hashFiles('vcpkg.json') }}
          vcpkgTriplet: ${{ matrix.triplet }}
       
      - name: Run CMake with vcpkg.json manifest
        uses: lukka/run-cmake@main
        with:
          cmakeListsOrSettingsJson: CMakeListsTxtAdvanced
          cmakeListsTxtPath: '${{ github.workspace }}/CMakeLists.txt'
          buildDirectory: '${{ env.buildDir }}'
          useVcpkgToolchainFile: true
          vcpkgTriplet: ${{ matrix.triplet }}
          cmakeAppendedArgs: ${{ matrix.cmakeOptions }}
          ctestCommandArgs: ${{ matrix.testOptions }}