name: Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  job:
    name: ${{ matrix.os }} build
    runs-on: ${{ matrix.os }}
    env:
      CMAKE_BUILD_DIR: ${{ github.workspace }}/build/
      LLVM_DIR: ${{ github.workspace }}/.llvm
      NINJA_DIR: ${{ github.workspace }}/.ninja
      VCPKG_ROOT: ${{ github.workspace }}/vcpkg
      VCPKG_ID: '30b217b1ede50f6c27b7234388114f4b0d60a3f7'
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-latest, windows-2022 ]
        include:
          - os: ubuntu-latest
            llvm_ver: 13
            ninja_ver: 1.10.2
            cmakeOptions: >
              -DCMAKE_C_COMPILER=${{ env.LLVM_DIR }}/bin/clang
              -DCMAKE_CXX_COMPILER=${{ env.LLVM_DIR }}/bin/clang++
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Restore ninja
        if: ${{ runner.os == 'Linux' }}
        id: cache-ninja
        uses: actions/cache@v2
        with:
          path: ${{ env.NINJA_DIR }}
          key: ${{ matrix.ninja_ver }}

     - uses: seanmiddleditch/gha-setup-ninja@master
        with:
          version: ${{ matrix.ninja_ver }}
          destination: ${{ env.NINJA_DIR }}

      - name: Restore LLVM
        if: ${{ runner.os == 'Linux' }}
        id: cache-llvm
        uses: actions/cache@v2
        with:
          path: ${{ env.LLVM_DIR }}
          key: ${{ matrix.llvm_ver }}

      - name: Set up Clang
        if: ${{ runner.os == 'Linux' }}
        uses: KyleMayes/install-llvm-action@master
        with:
          version: ${{ matrix.llvm_ver }}
          directory: ${{ env.LLVM_DIR }}
          cached: ${{steps.cache-llvm.outputs.cache-hit}}

      - name: Restore vcpkg installed.
        uses: actions/cache@v2
        with:
          path: |
            ${{ env.CMAKE_BUILD_DIR }}/vcpkg_installed/
          key: |
            ${{ env.VCPKG_ID }}-${{ hashFiles( 'vcpkg.json' ) }}

      - name: Setup vcpkg
        uses: lukka/run-vcpkg@v10
        with:
          vcpkgGitCommitId: ${{ env.VCPKG_ID }}
          appendedCacheKey: ${{ env.VCPKG_ID }}

      - uses: ilammy/msvc-dev-cmd@v1

      - name: Install dependencies and generate project files
        run: |
          cmake -S "${{ github.workspace }}" -B "${{ env.CMAKE_BUILD_DIR }}" -G Ninja -DCMAKE_TOOLCHAIN_FILE="${{ env.VCPKG_ROOT }}/scripts/buildsystems/vcpkg.cmake" ${{ matrix.cmakeOptions }}

      - name: Build
        run: |
          cmake --build "${{ env.CMAKE_BUILD_DIR }}"

      - name: Run test
        run: |
          cd ${{ env.CMAKE_BUILD_DIR }}
          set CTEST_OUTPUT_ON_FAILURE=1
          ctest -C Debug
