name: Build

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  job:
    name: ${{ matrix.os }} ${{ matrix.build-type }} build
    runs-on: ${{ matrix.os }}
    continue-on-error: false

    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-22.04, windows-latest]
        build-type: [Debug, Release]
        include:
          - os: ubuntu-22.04
            cmakeOptions: -DCMAKE_CXX_COMPILER=clang++ -DENABLE_CODE_COVERAGE=true
          - os: windows-latest
            cmakeOptions: -DENABLE_CLANG_TIDY=false # disable clang-tidy on Windows for MSVC

    steps:
      - uses: actions/checkout@v2

      - name: Upgrade Clang on Linux
        if: ${{ runner.os == 'Linux' }}
        run: |
          sudo apt update
          sudo apt upgrade clang

      - name: Upgrade MSVC on Windows
        if: ${{ runner.os == 'Windows' }}
        working-directory: C:\Program Files (x86)\Microsoft Visual Studio\Installer
        run: .\setup.exe update --add Microsoft.VisualStudio.Component.VC.Tools.x86.x64 --installPath "C:\Program Files\Microsoft Visual Studio\2022\Enterprise" -q --norestart --installWhileDownloading
        shell: pwsh

      - name: CMake build and test
        uses: ./.github/actions
        with:
          build-type: ${{ matrix.build-type }}
          config-option: ${{ matrix.cmakeOptions }}

      - name: Upload code coverage report
        env:
          CODACY_PROJECT_TOKEN: ${{ secrets.CODACY_PROJECT_TOKEN }}
        if: ${{ runner.os == 'Linux' }}
        run: bash <(curl -Ls https://coverage.codacy.com/get.sh) report -r ${{ inputs.build-dir }}/tests/stdsharpTestsCoverage.lcov
        shell: bash
