name: Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  job:          
    name: ${{ matrix.os }} build
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        include:
          - os: windows-latest
            triplet: x64-windows
            cmakeOptions: '-DBOOST_UT_DISABLE_MODULE'
            Target: blurringshadowTests
          - os: ubuntu-latest
            triplet: x64-linux
            cmakeOptions: -DCMAKE_CXX_COMPILER=gcc-10 -DCMAKE_BUILD_TYPE=RELEASE
            Target: blurringshadowTests
          - os: macos-latest
            triplet: x64-osx
            cmakeOptions: -DCMAKE_CXX_COMPILER=gcc-10
            Target: blurringshadowTests
    env:
      Target: blurringshadowTests
      buildDir: '${{ github.workspace }}/out'
      
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive

      - uses: lukka/get-cmake@latest

      - name: Restore artifacts, or setup vcpkg (do not install any package)
        uses: lukka/run-vcpkg@main
        id: runvcpkg
        with:
          setupOnly: true
          vcpkgGitCommitId: 'b2544fd780b2e9a05d903314cbbd37268ba43d81'
          # Ensure the cache key changes any time the content of the manifest file changes.
          appendedCacheKey: ${{ hashFiles( 'vcpkg.json' ) }}
          vcpkgTriplet: ${{ matrix.triplet }}
       
      - name: Run CMake with vcpkg.json manifest
        uses: lukka/run-cmake@main
        with:
          cmakeListsOrSettingsJson: CMakeListsTxtAdvanced
          cmakeListsTxtPath: '${{ github.workspace }}/CMakeLists.txt'
          buildDirectory: '${{ env.buildDir }}'
          useVcpkgToolchainFile: true
          vcpkgTriplet: ${{ matrix.triplet }}
          cmakeAppendedArgs : ${{ matrix.cmakeOptions }}

      - name: Build Project
        uses: lukka/run-cmake@main
        with:
          cmakeListsOrSettingsJson: CMakeListsTxtAdvanced
          cmakeListsTxtPath: '${{ github.workspace }}/CMakeLists.txt'
          useVcpkgToolchainFile: true
          vcpkgTriplet: ${{ matrix.triplet }}
          buildDirectory: '${{ env.buildDir }}'
          cmakeAppendedArgs : --build ${{ env.buildDir }} -t ${{ env.Target }}
