name: Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  job:          
    name: ${{ matrix.os }} build
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        include:
          - os: windows-latest
            triplet: x64-windows
            cmakeOptions: ''
          - os: ubuntu-latest
            triplet: x64-linux
            cmakeOptions: -D CMAKE_CXX_COMPILER=gcc-10 ENABLE_COVERAGE=ON CMAKE_BUILD_TYPE=Debug 
                --target blurringshadowTests blurringshadowTestsCoverage
          - os: macos-latest
            triplet: x64-osx
            cmakeOptions: -DCMAKE_CXX_COMPILER=gcc-10
    env:
      buildDir: '${{ github.workspace }}/out'

    steps:
      - uses: actions/checkout@v2

      - uses: lukka/get-cmake@latest

      - name: Restore artifacts, or setup vcpkg (do not install any package)
        uses: lukka/run-vcpkg@main
        id: runvcpkg
        with:
          setupOnly: true
          vcpkgGitCommitId: 'b2544fd780b2e9a05d903314cbbd37268ba43d81'
          # Ensure the cache key changes any time the content of the manifest file changes.
          appendedCacheKey: ${{ hashFiles( 'vcpkg.json' ) }}
          vcpkgTriplet: ${{ matrix.triplet }}
          
      - name: Run CMake with vcpkg.json manifest
        uses: lukka/run-cmake@main
        with:
          cmakeListsOrSettingsJson: CMakeListsTxtAdvanced
          cmakeListsTxtPath: '${{ github.workspace }}/CMakeLists.txt'
          useVcpkgToolchainFile: true
          buildDirectory: '${{ env.buildDir }}'
          vcpkgTriplet: ${{ matrix.triplet }}
          cmakeAppendedArgs : ${{ matrix.cmakeOptions }}

          
      - name: collect code coverage
        if: ${{ runner.os == 'Linux' }}
        uses: codecov/codecov-action@v1
        with:
          fail_ci_if_error: true
          directory: '{{ env.buildDir }}'
          verbose: true
